export const defaultTargetList = [
    { id: "google", name: "Google", url: "https://www.google.com/search?q=%s" },
    { id: "bing", name: "Bing", url: "https://www.bing.com/search?q=%s" },
    { id: "reddit", name: "Reddit", url: "https://www.reddit.com/search/?q=%s" },
    { id: "youtube", name: "YouTube", url: "https://www.youtube.com/results?search_query=%s&page={startPage?}&utm_source=opensearch" },
    { id: "bluesky", name: "Bluesky", url: "https://bsky.app/search?q=%s" },
    { id: "threads", name: "Threads", url: "https://www.threads.net/search?q=%s&serp_type=default" },
    { id: "instagram", name: "Instagram", url: "https://www.instagram.com/explore/search/keyword/?q=%s" },
    { id: "tiktok", name: "TikTok", url: "https://www.tiktok.com/search?q=%s" },
    { id: "x", name: "X", url: "https://x.com/search?q=%s" },
    { id: "mastodon", name: "Mastodon", url: "https://mastodon.social/search?q=%s" },
    { id: "stackoverflow", name: "Stack Overflow", url: "https://stackoverflow.com/search?q=%s" },
    { id: "amazon", name: "Amazon", url: "https://www.amazon.com/s?k=%s" },
    { id: "duckduckgo", name: "Duck Duck Go", url: "https://duckduckgo.com/?q=%s" },
    { id: "github", name: "GitHub", url: "https://github.com/search?q=%s&ref=opensearch" },
    { id: "hackernews", name: "Hacker News", url: "https://hn.algolia.com/?q=%s" },
    { id: "facebook", name: "Facebook", url: "https://www.facebook.com/search/top?q=%s" },
    { id: "wikipedia", name: "Wikipedia", url: "https://en.wikipedia.org/wiki/%s" },
    { id: "superuser", name: "Super User", url: "https://superuser.com/search?q=%s" },
    { id: "ultimateguitar", name: "Ultimate Guitar", url: "https://www.ultimate-guitar.com/search.php?search_type=title&value=%s" }
];